/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkpoints.proto

package com.google.cloud.pubsublite.flink.proto;

public final class Checkpoints {
  private Checkpoints() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\021checkpoints.proto\022\035google.cloud.pubsub"
          + "lite.flink\"\272\001\n\037SubscriptionPartitionSpli"
          + "tProto\022\024\n\014subscription\030\001 \001(\t\022\021\n\tpartitio"
          + "n\030\002 \001(\003\022T\n\005start\030\003 \001(\0132E.google.cloud.pu"
          + "bsublite.flink.SubscriptionPartitionSpli"
          + "tProto.Cursor\032\030\n\006Cursor\022\016\n\006offset\030\001 \001(\003B"
          + "+\n\'com.google.cloud.pubsublite.flink.pro"
          + "toP\001b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor,
            new java.lang.String[] {
              "Subscription", "Partition", "Start",
            });
    internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_descriptor =
        internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_descriptor,
            new java.lang.String[] {
              "Offset",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
