/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkpoints.proto

package com.google.cloud.pubsublite.flink.proto;

/** Protobuf type {@code google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto} */
public final class SubscriptionPartitionSplitProto extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto)
    SubscriptionPartitionSplitProtoOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use SubscriptionPartitionSplitProto.newBuilder() to construct.
  private SubscriptionPartitionSplitProto(
      com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private SubscriptionPartitionSplitProto() {
    subscription_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new SubscriptionPartitionSplitProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private SubscriptionPartitionSplitProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              subscription_ = s;
              break;
            }
          case 16:
            {
              partition_ = input.readInt64();
              break;
            }
          case 26:
            {
              com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.Builder
                  subBuilder = null;
              if (start_ != null) {
                subBuilder = start_.toBuilder();
              }
              start_ =
                  input.readMessage(
                      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                          .parser(),
                      extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(start_);
                start_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.pubsublite.flink.proto.Checkpoints
        .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.pubsublite.flink.proto.Checkpoints
        .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.class,
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Builder.class);
  }

  public interface CursorOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 offset = 1;</code>
     *
     * @return The offset.
     */
    long getOffset();
  }
  /** Protobuf type {@code google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor} */
  public static final class Cursor extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor)
      CursorOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Cursor.newBuilder() to construct.
    private Cursor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Cursor() {}

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new Cursor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Cursor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8:
              {
                offset_ = input.readInt64();
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.pubsublite.flink.proto.Checkpoints
          .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.pubsublite.flink.proto.Checkpoints
          .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.class,
              com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.Builder
                  .class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <code>int64 offset = 1;</code>
     *
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (offset_ != 0L) {
        output.writeInt64(1, offset_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, offset_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj
          instanceof
          com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor)) {
        return super.equals(obj);
      }
      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor other =
          (com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor) obj;

      if (getOffset() != other.getOffset()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getOffset());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor)
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.CursorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.google.cloud.pubsublite.flink.proto.Checkpoints
            .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.cloud.pubsublite.flink.proto.Checkpoints
            .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                    .class,
                com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                    .Builder.class);
      }

      // Construct using
      // com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        offset_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.google.cloud.pubsublite.flink.proto.Checkpoints
            .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_Cursor_descriptor;
      }

      @java.lang.Override
      public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
          getDefaultInstanceForType() {
        return com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
          build() {
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
          buildPartial() {
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor result =
            new com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor(
                this);
        result.offset_ = offset_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other
            instanceof
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor) {
          return mergeFrom(
              (com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor)
                  other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor other) {
        if (other
            == com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                .getDefaultInstance()) return this;
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
            parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long offset_;
      /**
       * <code>int64 offset = 1;</code>
       *
       * @return The offset.
       */
      @java.lang.Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>int64 offset = 1;</code>
       *
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {

        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 offset = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearOffset() {

        offset_ = 0L;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor)
    }

    // @@protoc_insertion_point(class_scope:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor)
    private static final com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
            .Cursor
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor();
    }

    public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cursor> PARSER =
        new com.google.protobuf.AbstractParser<Cursor>() {
          @java.lang.Override
          public Cursor parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Cursor(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Cursor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cursor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public static final int SUBSCRIPTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object subscription_;
  /**
   *
   *
   * <pre>
   * The Pub/Sub Lite subscription path for this split.
   * </pre>
   *
   * <code>string subscription = 1;</code>
   *
   * @return The subscription.
   */
  @java.lang.Override
  public java.lang.String getSubscription() {
    java.lang.Object ref = subscription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subscription_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The Pub/Sub Lite subscription path for this split.
   * </pre>
   *
   * <code>string subscription = 1;</code>
   *
   * @return The bytes for subscription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSubscriptionBytes() {
    java.lang.Object ref = subscription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      subscription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITION_FIELD_NUMBER = 2;
  private long partition_;
  /**
   *
   *
   * <pre>
   * The partition corresponding to this split.
   * </pre>
   *
   * <code>int64 partition = 2;</code>
   *
   * @return The partition.
   */
  @java.lang.Override
  public long getPartition() {
    return partition_;
  }

  public static final int START_FIELD_NUMBER = 3;
  private com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor start_;
  /**
   *
   *
   * <pre>
   * The cursor for this split.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
   *
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return start_ != null;
  }
  /**
   *
   *
   * <pre>
   * The cursor for this split.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
   *
   * @return The start.
   */
  @java.lang.Override
  public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor getStart() {
    return start_ == null
        ? com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
            .getDefaultInstance()
        : start_;
  }
  /**
   *
   *
   * <pre>
   * The cursor for this split.
   * </pre>
   *
   * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
   */
  @java.lang.Override
  public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.CursorOrBuilder
      getStartOrBuilder() {
    return getStart();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getSubscriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subscription_);
    }
    if (partition_ != 0L) {
      output.writeInt64(2, partition_);
    }
    if (start_ != null) {
      output.writeMessage(3, getStart());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSubscriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subscription_);
    }
    if (partition_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, partition_);
    }
    if (start_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getStart());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto)) {
      return super.equals(obj);
    }
    com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto other =
        (com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto) obj;

    if (!getSubscription().equals(other.getSubscription())) return false;
    if (getPartition() != other.getPartition()) return false;
    if (hasStart() != other.hasStart()) return false;
    if (hasStart()) {
      if (!getStart().equals(other.getStart())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getSubscription().hashCode();
    hash = (37 * hash) + PARTITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getPartition());
    if (hasStart()) {
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
      parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
      parseDelimitedFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto)
      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.pubsublite.flink.proto.Checkpoints
          .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.pubsublite.flink.proto.Checkpoints
          .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.class,
              com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Builder
                  .class);
    }

    // Construct using
    // com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      subscription_ = "";

      partition_ = 0L;

      if (startBuilder_ == null) {
        start_ = null;
      } else {
        start_ = null;
        startBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.pubsublite.flink.proto.Checkpoints
          .internal_static_google_cloud_pubsublite_flink_SubscriptionPartitionSplitProto_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
        getDefaultInstanceForType() {
      return com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
          .getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto build() {
      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto result =
          buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto buildPartial() {
      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto result =
          new com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto(this);
      result.subscription_ = subscription_;
      result.partition_ = partition_;
      if (startBuilder_ == null) {
        result.start_ = start_;
      } else {
        result.start_ = startBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other
          instanceof com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto) {
        return mergeFrom(
            (com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto other) {
      if (other
          == com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
              .getDefaultInstance()) return this;
      if (!other.getSubscription().isEmpty()) {
        subscription_ = other.subscription_;
        onChanged();
      }
      if (other.getPartition() != 0L) {
        setPartition(other.getPartition());
      }
      if (other.hasStart()) {
        mergeStart(other.getStart());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto)
                e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object subscription_ = "";
    /**
     *
     *
     * <pre>
     * The Pub/Sub Lite subscription path for this split.
     * </pre>
     *
     * <code>string subscription = 1;</code>
     *
     * @return The subscription.
     */
    public java.lang.String getSubscription() {
      java.lang.Object ref = subscription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The Pub/Sub Lite subscription path for this split.
     * </pre>
     *
     * <code>string subscription = 1;</code>
     *
     * @return The bytes for subscription.
     */
    public com.google.protobuf.ByteString getSubscriptionBytes() {
      java.lang.Object ref = subscription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        subscription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The Pub/Sub Lite subscription path for this split.
     * </pre>
     *
     * <code>string subscription = 1;</code>
     *
     * @param value The subscription to set.
     * @return This builder for chaining.
     */
    public Builder setSubscription(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      subscription_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The Pub/Sub Lite subscription path for this split.
     * </pre>
     *
     * <code>string subscription = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSubscription() {

      subscription_ = getDefaultInstance().getSubscription();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The Pub/Sub Lite subscription path for this split.
     * </pre>
     *
     * <code>string subscription = 1;</code>
     *
     * @param value The bytes for subscription to set.
     * @return This builder for chaining.
     */
    public Builder setSubscriptionBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      subscription_ = value;
      onChanged();
      return this;
    }

    private long partition_;
    /**
     *
     *
     * <pre>
     * The partition corresponding to this split.
     * </pre>
     *
     * <code>int64 partition = 2;</code>
     *
     * @return The partition.
     */
    @java.lang.Override
    public long getPartition() {
      return partition_;
    }
    /**
     *
     *
     * <pre>
     * The partition corresponding to this split.
     * </pre>
     *
     * <code>int64 partition = 2;</code>
     *
     * @param value The partition to set.
     * @return This builder for chaining.
     */
    public Builder setPartition(long value) {

      partition_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The partition corresponding to this split.
     * </pre>
     *
     * <code>int64 partition = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPartition() {

      partition_ = 0L;
      onChanged();
      return this;
    }

    private com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor start_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor,
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.Builder,
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.CursorOrBuilder>
        startBuilder_;
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     *
     * @return Whether the start field is set.
     */
    public boolean hasStart() {
      return startBuilder_ != null || start_ != null;
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     *
     * @return The start.
     */
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
        getStart() {
      if (startBuilder_ == null) {
        return start_ == null
            ? com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                .getDefaultInstance()
            : start_;
      } else {
        return startBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    public Builder setStart(
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        start_ = value;
        onChanged();
      } else {
        startBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    public Builder setStart(
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.Builder
            builderForValue) {
      if (startBuilder_ == null) {
        start_ = builderForValue.build();
        onChanged();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    public Builder mergeStart(
        com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor value) {
      if (startBuilder_ == null) {
        if (start_ != null) {
          start_ =
              com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                  .newBuilder(start_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          start_ = value;
        }
        onChanged();
      } else {
        startBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    public Builder clearStart() {
      if (startBuilder_ == null) {
        start_ = null;
        onChanged();
      } else {
        start_ = null;
        startBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.Builder
        getStartBuilder() {

      onChanged();
      return getStartFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.CursorOrBuilder
        getStartOrBuilder() {
      if (startBuilder_ != null) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        return start_ == null
            ? com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                .getDefaultInstance()
            : start_;
      }
    }
    /**
     *
     *
     * <pre>
     * The cursor for this split.
     * </pre>
     *
     * <code>.google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto.Cursor start = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor,
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor.Builder,
            com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.CursorOrBuilder>
        getStartFieldBuilder() {
      if (startBuilder_ == null) {
        startBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor,
                com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto.Cursor
                    .Builder,
                com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
                    .CursorOrBuilder>(getStart(), getParentForChildren(), isClean());
        start_ = null;
      }
      return startBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.pubsublite.flink.SubscriptionPartitionSplitProto)
  private static final com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
      DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE =
        new com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto();
  }

  public static com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
      getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscriptionPartitionSplitProto> PARSER =
      new com.google.protobuf.AbstractParser<SubscriptionPartitionSplitProto>() {
        @java.lang.Override
        public SubscriptionPartitionSplitProto parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SubscriptionPartitionSplitProto(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<SubscriptionPartitionSplitProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscriptionPartitionSplitProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.pubsublite.flink.proto.SubscriptionPartitionSplitProto
      getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
